feature_extract_enable : 0
point_filter_num : 1 #2
max_iteration : 10 #5
dense_map_enable : 1
filter_size_surf : 0.1  #0.15
filter_size_map : 0.3
cube_side_length : 1000
grid_size : 40
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 300 # 78 100 156 300
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
pose_output_en: false
delta_time: 0.0
cam_fx: 1302.642537
cam_fy: 1302.339408
cam_cx: 660.833204
cam_cy: 496.071276

common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"

preprocess:
    lidar_type: 1 # 1:Livox LiDAR  2:VELO16  3:OUST64  4:XT32  5:Mid360
    scan_line: 6 # 16  64  32
    blind: 0.5 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    extrinsic_T: [ -0.011, -0.02329, 0.04412 ] # horizon 0.05512, 0.02226, -0.0297 # mid360 -0.011, -0.02329, 0.04412 # avia 0.04165, 0.02326, -0.0284    -0.011, -0.02329, 0.04412
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

pcd_save:
    pcd_save_en: false

camera:
    img_topic: /hk_camera_node/image_raw
    Rcl: [0.0771028,-0.995625,0.0527743,
         0.00270042,-0.0527232,-0.998606, 
         0.997019,0.0771378,-0.0013765]  
    Pcl: [-0.224801, 0.0790971, 0.297322]
    
